# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 2.7
env:
 - TOX_ENV=py
 - TOX_ENV=py24
 - TOX_ENV=py25
 - TOX_ENV=py26
 - TOX_ENV=py27
 - TOX_ENV=py30
 - TOX_ENV=py31
 - TOX_ENV=py32
 - TOX_ENV=py33
 - TOX_ENV=py34
 - TOX_ENV=py34
 - TOX_ENV=jython
 - TOX_ENV=pypy 
 - TOX_ENV=pypy3


install:
 - pip install tox
script:
 - tox -e $TOX_ENV


