# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 2.7
env:
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.3
  - TRAVIS_PYTHON_VERSION=3.4
  - TRAVIS_PYTHON_VERSION=3.5
install:
 - pip install tox
script:
 - tox -e $TOX_ENV


