# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
sudo: false
os:
        -linux
git:
        submodules: false
before_install:
        - git submodule update --init --recursive
python: 3.5

env:
  - TRAVIS_PYTHON_VERSION=2.7
  - TRAVIS_PYTHON_VERSION=3.3
  - TRAVIS_PYTHON_VERSION=3.4
  - TRAVIS_PYTHON_VERSION=3.5

notifications:
  email:
    recipients:
        - devin.etcitty@columbia.edu
    on_success: change
    on_failure: always


# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U py.test

# command to run tests, e.g. python setup.py test
script: py.test -e ${TRAVIS_PYTHON_VERSION}


